import React from "react";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import AllRoomsCard from "@/components/AllRoomsCard";
import Link from "next/link";
import { Button } from "@heroui/react";
import { IoMdAdd } from "react-icons/io";

export const metadata = {
  title: "StudyNook || MyListing",
  description: "Generated by create next app",
};

const MyListingPage = async () => {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  const user = session?.user;

  const res = await fetch(
    `${process.env.NEXT_PUBLIC_SERVER_URL}/my-rooms/${user.id}`,
    {
      cache: "no-store",
      headers: {
        Authorization: `Bearer ${session?.session?.token}`,
      },
    },
  );

  if (!res.ok) {
    throw new Error("Failed to fetch rooms");
  }

  const rooms = await res.json();

  return (
    <div className="min-h-screen bg-zinc-50 py-10">
      <div className="max-w-7xl mx-auto px-6">
        <div className="mb-10 flex justify-between items-center">
          <div>
            <h1 className="text-4xl font-bold text-gray-900">My Listings</h1>

            <p className="text-gray-600 mt-2">Manage your added study rooms</p>
          </div>

          <Link href="/addRoom">
            <Button
              className="h-12 px-6 rounded-xl text-white font-medium"
              style={{
                background: "linear-gradient(135deg, #7C3AED, #3B82F6)",
              }}
            >
              <IoMdAdd size={20} />
              Add Room
            </Button>
          </Link>
        </div>

        {rooms?.length === 0 ? (
          <div className="bg-white rounded-3xl py-20 text-center border">
            <h2 className="text-2xl font-semibold">No Listings Found</h2>

            <p className="text-gray-500 mt-2">
              You haven't added any rooms yet
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-8">
            {rooms.map((room) => (
              <AllRoomsCard key={room._id} room={room} />
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default MyListingPage;
